---
- name: make consul directory
  become: yes
  file:
    dest: /opt/consul
    state: directory

- name: make consul data directory
  become: yes
  file:
    dest: /opt/consul/data
    state: directory

- name: split ips by commas
  set_fact:
    nomad_master_server_ips_list: "{{ nomad_master_server_ips.split(',') }}"

- name: put consul configuration in place
  become: yes
  template:
    dest: /opt/consul/consul.json
    src: consul.json.j2
    mode: 0644

- name: put consul in upstart services
  become: yes
  template:
    dest: /etc/init/consul.conf
    src: consul.conf.j2
    mode: 0644

- name: start consul
  become: yes
  service:
    name: consul
    state: restarted
